### ISSUE TITLE
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by Pete1138** [vndevpro/MiniProfiler.Integrations#1]
I'm occasionally getting an InvalidOperationException when calling GetCommands().
Is is because the ExecutedCommands/FailedCommands list needs ToList() called before it is enumerated?

**Comment by juanonsoftware** [comment]
Sorry for this late response ;)
Did you run your app in multi thread context? So I think it may need a lock on adding / getting commands.
