### ISSUE TITLE
IDbProfiler data type is not found in .Net Core Console project

### ISSUE THREAD

**Issue by jramirezqat** [vndevpro/MiniProfiler.Integrations#3]
Cannot use `ProfiledDbconnectionFactory.New()` because the data type `StackExchange.Profiling.Data.IDbProfiler` is not found.  It claims to be in a package named MiniProfiler, but said package is not found by Visual Studio.

I wonder if this is a problem specific to .Net Core.  Thanks.

**Comment by erotavlas** [comment]
I installed the Nuget package in a .NET 4.6 application and placed this line in my code

var profiler = CustomDbProfiler.Current;

and it can't find the CustomDbProfiler object.

**Comment by pmbanka** [comment]
@erotavlas  https://github.com/vndevpro/MiniProfiler.Integrations/blob/f335fd8cb2f3a9b50e3c107084853ce943099201/MiniProfiler.Integrations/CustomDbProfiler.cs#L7

**Comment by lxman** [comment]
I am getting something that may be related here. I am trying to create a console app in Rider for .NET Core 3.1. I am getting an error that 'Argument type 'MiniProfiler.Integrations.CustomDbProfiler' is not assignable to parameter type 'StackExchange.Profiling.Data.IDbProfiler''
![Code](https://user-images.githubusercontent.com/20031555/94999954-f8a32800-058a-11eb-8fea-2801e63e5509.png)

**Comment by juanonsoftware** [comment]
Hi there,

I didn't have anay chance to update the test to netcore3.1, maybe you can check if MiniProfiler is still on 3.2.0.x version?

I'll take some spare to upgrade this and to support netcore.

**Comment by juanonsoftware** [comment]
Hi,
I have created a new version of the library and now it supports NetStandard20. You can install new version or check source code with sample project. Hope this helps !

Install-Package MiniProfiler.Integrations -Version 2.5.0
