### ISSUE TITLE
Reference to type 'IDbProfiler' claims it is defined in 'MiniProfiler', but it could not be found

### ISSUE THREAD

**Issue by michaelsync** [vndevpro/MiniProfiler.Integrations#4]
Hi,

I am getting this error ```Reference to type 'IDbProfiler' claims it is defined in 'MiniProfiler', but it could not be found``` at this line ```using (var dbConnection = ProfiledDbConnectionFactory.New(new SqlServerDbConnectionFactory(_connectionString), profiler))``` after installing ```MiniProfiler.Integrations```.

My project is asp.net core 2.1. 

I tried adding MiniProfiler package, MiniProfiler.Shared, MiniProfiler.Aspnet.Core, MiniProfiler provider sql server but didn't work. 

Did I miss out on something?

**Comment by juanonsoftware** [comment]
Hi,
I have created a new version of the library and now it supports NetStandard20. You can install new version or check source code with sample project. Hope this helps !

Install-Package MiniProfiler.Integrations -Version 2.5.0
